### ISSUE TITLE
Re-add 'only decode' functionality

### ISSUE THREAD

**Issue by joelsdc** [jitsi/luajwtjitsi#5]
Hi,

Since v3.0 the `decode` functionality [has been removed](https://github.com/jitsi/luajwtjitsi/commit/d3eb5f326b7c445d8369e25c30ca544f3400ff61) but the README still states that it exists

```
-- only decode
local unsafe, err = jwt.decode(token)
```

* Any chance you can re-add that functionality?
* Was removing it just part of a cleanup or was the code really insecure?
* If the previous code was **insecure**, maybe we can find a way of keeping that functionality but without compromising security? 

Thanks!

**Comment by joelsdc** [comment]
For now I've pinned to v2.0 but I'd love to know if it's viable to add it back.

**Comment by saghul** [comment]
It will not be coming back because more extra checks are necessary, it's unsafe. We'll fixup the README.
